### ISSUE TITLE
Color ROS overlay warning message

### ISSUE THREAD

**Issue by DFriend01** [UBCSailbot/sailbot_workspace#148]
### Purpose

Coloring the warning message for the ROS overlay is good for UX.

### Changes

Change the following line:
https://github.com/UBCSailbot/sailbot_workspace/blob/2b1bf8ca3e9b3f615a10091a7dc608a340e36565/.devcontainer/base-dev/update-bashrc.sh#L19

To this:

```bash
echo "    echo -e \"\\\e[1;33mWARNING: Can't find the ROS workspace overlay: build then run 'source $ROS_WORKSPACE/install/local_setup.bash'\\\e[0m\"" >> $HOME/.bashrc 
```

To test this, rather than rebuilding the base image, manually run `update-bashrc.sh` in your terminal and then resource the bashrc:

```bash
./.devcontainer/base-dev/update-bashrc.sh
source ~/.bashrc
```

**Important:** This warning message is only thrown when the ROS overlay doesn't exist. If you have already built any ROS packages in your copy of sailbot workspace, run the `purge` task in vscode before following the above steps.

**Comment by patrick-5546** [comment]
Last step after verifying your changes is to build a new dev image: https://github.com/UBCSailbot/sailbot_workspace/tree/main/.devcontainer/base-dev#how-to-build
