### ISSUE TITLE
Explore ROS package dependencies

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/sailbot_workspace#242]
### Purpose

Clean up dependencies

### Changes

Is it possible to specify the pip packages required in the ROS package and have those be installed when running the setup task?

### Resources

- https://docs.ros.org/en/humble/Tutorials/Beginner-Client-Libraries/Creating-Your-First-ROS2-Package.html#customize-package-xml

**Comment by SPDonaghy** [comment]
Update: I have moved 3 dependencies given by Henry to package.xml in network_systems. 
Currently running the build images workflow on the new image with those dependencies removed from the dockerfile.
Once that is done, I will rebuild with the new image and test the package to ensure there are no errors.
