### ISSUE TITLE
Wingsail Controller Implementation

### ISSUE THREAD

**Issue by DFriend01** [UBCSailbot/sailbot_workspace#301]
### Purpose

This tasklist tracks the wingsail controller implementation. It aligns with the goals on the Milanote time for the term between January 2024 and April 2024. When all tasks on this list are complete, the wingsail controller is considered implemented and integrated.

### Tasks

- [x] Supporting Logic
    - [x] UBCSailbot/controller#20
    - [x] UBCSailbot/sailbot_workspace#303
- [x] Integration
    - [x] UBCSailbot/controller#22
    - [x] UBCSailbot/sailbot_workspace#302

**Comment by alberto-escobar** [comment]
All tasks complete, I will close this issue. 
🎉🎉🎉🎉🚀🚀🚀🚀
