### ISSUE TITLE
Sail Controller Class

### ISSUE THREAD

**Issue by DFriend01** [UBCSailbot/sailbot_workspace#303]
### Purpose

This class is meant to compute the trim tab angle that will be published to the ROS network.

### Description

**Note:** The completion of this issue depends on UBCSailbot/controller#20. To get started, placeholder code can be used until the `LUT` class is available for use.

Remember to take inspiration from the controller prototype that was implemented last term. This will guide your implementation. Create a class for the sail controller in `controller/wingsail/controllers.py`.

**Inputs:**
- The lookup table to use for interpolation

**Class Functionality:**
- The main public method should return the desired trim tab angle. Implement any private methods you wish to help with this.

**Tests:**
- Implement your tests in `tests/unit/wingsail/test_controllers.py`. See the boat simulator for examples on how to implement tests using pytest.

### Resources

- [Pytest getting started guide](https://docs.pytest.org/en/7.4.x/getting-started.html#group-multiple-tests-in-a-class)

**Comment by alberto-escobar** [comment]
Worked on resolving this issue in PR #327
