### ISSUE TITLE
Support ARM computers

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/sailbot_workspace#31]
Push ARM versions of the docker images so that this workspace can run natively on ARM computers like the M1 Macbooks.

### Resources
- https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by patrick-5546** [comment]
Not a priority until we have someone on the team that uses an ARM computer

**Comment by patrick-5546** [comment]
@hhenry01 can we use docker containers on the main computer?

**Comment by hhenry01** [comment]
Yes, but there's not really necessary. Ideally we would compile the code on our own computers and copy the binaries over.

**Comment by patrick-5546** [comment]
Resolve blockers:
- [ ] Installing OMPL with Python bindings: see issue 958 in ompl repo

Resources for building multi-arch docker images
- https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
- https://billglover.me/notes/build-multi-arch-docker-images/
