### ISSUE TITLE
Unit tests start 2 http servers on the same port

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/sailbot_workspace#363]
### Description

A recent NET PR causes the test task to fail: both NET and PATH unit tests start http servers on port 8081

#### Expected Behavior

Test task should pass

#### Actual Behavior

On my machine the local pathfinding unit tests run after net, and I get this error:
![image](https://github.com/UBCSailbot/sailbot_workspace/assets/65756895/df6ed9be-db22-4ba3-9fc2-e6bef71f1425)

### Steps to Reproduce

1. Run the test task

### Relevant Code

- NET: https://github.com/UBCSailbot/sailbot_workspace/blob/main/src/network_systems/scripts/http_echo_server.py
- PATH: https://github.com/UBCSailbot/sailbot_workspace/blob/main/src/local_pathfinding/test/post_server.py
    - Temporary substitute for NET global path endpoint

### Potential Solutions

@hhenry01 any ideas? Is the NET global path endpoint working yet? Or should one of the servers run on a different port

**Comment by hhenry01** [comment]
I'm assuming this happens because both the NET and PATH unit tests are ran in parallel. We would either need to run the servers on different ports for unit testing only or run the NET and PATH tests sequentially.

**Comment by patrick-5546** [comment]
What's the net server for? Is it supposed to mimic the webhook server as well which will run on 8081?

**Comment by hhenry01** [comment]
Yes. Virtual Iridium needs an active server or else it will crash.

**Comment by patrick-5546** [comment]
@SPDonaghy we should use a different port then until it's implemented on the net side

**Comment by SPDonaghy** [comment]
> @SPDonaghy we should use a different port then until it's implemented on the net side

Sounds good, I can make that change tomorrow
