### ISSUE TITLE
OMPL Python bindings not properly installed on ARM devices

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/sailbot_workspace#398]
### Description

OMPL is a pathfinding dependency. This means that our software can't run on ARM devices such as the RPI 4 and newer macbooks

### Verification Steps
- [ ] `./scripts/deployment/start_containers.sh --website --interactive` then `python3` then `import ompl.util as ou` has no errors
- [ ] `./scripts/deployment/start_containers.sh --website --interactive` then run `./scripts/test.sh` and all tests pass
- [ ] `./scripts/deployment/start_containers.sh --website` runs the global launch file
- [ ] Try in dev container on my personal computer as well

### Resources

- #319 
- #396 
- https://github.com/ompl/ompl/issues/1116

**Comment by johnnynunez** [comment]
pygcc we upgrading to 24.04 and castxml 0.6.11 and for aarch64. In the future it could be installed as pip install

**Comment by SPDonaghy** [comment]
> pygccxml: we upgrading to 24.04 and castxml 0.6.11 and for aarch64. In the future it could be installed as pip install so ompl will be compatible [ompl/ompl#1234](https://github.com/ompl/ompl/pull/1234)

Do you think its likely we could see support for ompl on aarch64 in the future? We've gone ahead and made [our own bindings](https://github.com/UBCSailbot/sailbot_workspace/blob/main/src/local_pathfinding/src/build/ompl_bindings.cpp) using pybind11 which seems to work for now.

**Comment by johnnynunez** [comment]
> > pygccxml: we upgrading to 24.04 and castxml 0.6.11 and for aarch64. In the future it could be installed as pip install so ompl will be compatible [ompl/ompl#1234](https://github.com/ompl/ompl/pull/1234)
> 
> Do you think its likely we could see support for ompl on aarch64 in the future? We've gone ahead and made [our own bindings](https://github.com/UBCSailbot/sailbot_workspace/blob/main/src/local_pathfinding/src/build/ompl_bindings.cpp) using pybind11 which seems to work for now.

Yeah for sure! I’m supporting

**Comment by johnnynunez** [comment]
@SPDonaghy @patrick-5546 done it is working: with castxml 0.6.11, also for macos
it is working https://github.com/johnnynunez/ompl/actions/runs/13643981441
close :)

**Comment by SPDonaghy** [comment]
@johnnynunez Oh wow that's fantastic! Thank-you for your support! 🚀

**Comment by johnnynunez** [comment]
> [@johnnynunez](https://github.com/johnnynunez) Oh wow that's fantastic! Thank-you for your support! 🚀

Yeap! Now ompl has my PR merged

**Comment by johnnynunez** [comment]
OMPL 1.7.0 is coming

**Comment by johnnynunez** [comment]
wheels here: https://pypi.jetson-ai-lab.dev/jp6/cu128/ompl/1.6.0

**Comment by johnnynunez** [comment]
official wheels @SPDonaghy https://github.com/ompl/ompl/releases/tag/prerelease
