### ISSUE TITLE
Create "wipe" VS Code task

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/sailbot_workspace#64]
### Purpose

When switching to a branch with different build dependencies, it may be necessary to wipe the workspace of all generated code.

### Changes

- Run "clean" task (actually may not be needed)
- Run "purge" task
- Delete repositories in `src/` **only if there are no uncommitted changes, else fail**

### Relevant files
- Tasks are in the VS Code workspace file

### Resources
- https://code.visualstudio.com/docs/editor/tasks#_custom-tasks

**Comment by DFriend01** [comment]
@patrick-5546 Is it fine to just combine clean and purge into one task, or do you still want to wipe out directories in `src`? I'm just tired of running both clean and purge, so I want a task that does both :-)

**Comment by patrick-5546** [comment]
Yea feel free to assign yourself and make a PR

**Comment by DFriend01** [comment]
Turns out that `purge` is a more thorough version of `clean`. If we are not implementing the third change specified in the issue documentation, then there is no point in implementing `wipe`.

**Comment by patrick-5546** [comment]
Yea I don't see a usecase for the third point. If you don't either, you can close this PR and use purge instead of clean+purge

**Comment by DFriend01** [comment]
I briefly tried a solution but it's overcomplicated for what it's worth. I'm opting to close this issue.
