### ISSUE TITLE
Add back ament_pep257

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/sailbot_workspace#78]
### Purpose

The ament_pep257 linter was removed from our CI in #77 because it is broken. Once the fix has been published, we should add it back.

### Changes

- `linter: [lint_cmake, xmllint, flake8, pep257]` in tests.yaml
- Make ament_pep257 required in branch protection rules

### Resources

- The latest version of ament_lint for humble is 0.12.4: https://index.ros.org/p/ament_lint/#humble-overview
- The fix can be found in 0.12.5: https://github.com/ament/ament_lint/compare/0.12.4...0.12.5

**Comment by hhenry01** [comment]
Ditto for the network-systems repo.

**Comment by patrick-5546** [comment]
Is there a way to install the latest version if it's not in apt repostiory?
